

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24"},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.IBRAM_U"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.OBRAM_U"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.OBRAM_1_U"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.OBRAM_2_U"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.OBRAM_3_U"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.OBRAM_4_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.OBRAM_5_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48"},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.WBRAM_5_U"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.WBRAM_4_U"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.WBRAM_3_U"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.WBRAM_2_U"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.WBRAM_1_U"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.WBRAM_U"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fadd_32ns_32ns_32_4_full_dsp_1_U6"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fadd_32ns_32ns_32_4_full_dsp_1_U7"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fadd_32ns_32ns_32_4_full_dsp_1_U8"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fmul_32ns_32ns_32_3_max_dsp_1_U10"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fmul_32ns_32ns_32_3_max_dsp_1_U11"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fmul_32ns_32ns_32_3_max_dsp_1_U12"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fmul_32ns_32ns_32_3_max_dsp_1_U13"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.fmul_32ns_32ns_32_3_max_dsp_1_U14"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.hconv1_local_local_U"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.hconv1_1_local_local_U"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.hconv1_2_local_local_U"},
	{"ID" : "31", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.hconv1_3_local_local_U"},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.hconv1_4_local_local_U"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.fdiv_32ns_32ns_32_9_no_dsp_1_U29"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.fexp_32ns_32ns_32_8_full_dsp_1_U30"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.sparsemux_13_3_32_1_1_U31"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.urem_10ns_4ns_3_14_1_U32"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.mul_13ns_15ns_27_1_1_U33"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.mac_muladd_10ns_3ns_10ns_13_4_1_U34"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.fadd_32ns_32ns_32_4_full_dsp_1_U48"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.fadd_32ns_32ns_32_4_full_dsp_1_U49"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.fadd_32ns_32ns_32_4_full_dsp_1_U50"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_CONVOLUTION_LAYER_1_fu_24.fmul_32ns_32ns_32_3_max_dsp_1_U51"}]}
set DependenceCheckSize 0
