-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lenet5_CONVOLUTION_LAYER_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_layer_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_layer_ce0 : OUT STD_LOGIC;
    input_layer_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of lenet5_CONVOLUTION_LAYER_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal IBRAM_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal IBRAM_ce0 : STD_LOGIC;
    signal IBRAM_we0 : STD_LOGIC;
    signal IBRAM_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OBRAM_ce0 : STD_LOGIC;
    signal OBRAM_we0 : STD_LOGIC;
    signal OBRAM_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_ce1 : STD_LOGIC;
    signal OBRAM_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OBRAM_1_ce0 : STD_LOGIC;
    signal OBRAM_1_we0 : STD_LOGIC;
    signal OBRAM_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_1_ce1 : STD_LOGIC;
    signal OBRAM_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OBRAM_2_ce0 : STD_LOGIC;
    signal OBRAM_2_we0 : STD_LOGIC;
    signal OBRAM_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_2_ce1 : STD_LOGIC;
    signal OBRAM_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OBRAM_3_ce0 : STD_LOGIC;
    signal OBRAM_3_we0 : STD_LOGIC;
    signal OBRAM_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_3_ce1 : STD_LOGIC;
    signal OBRAM_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OBRAM_4_ce0 : STD_LOGIC;
    signal OBRAM_4_we0 : STD_LOGIC;
    signal OBRAM_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_4_ce1 : STD_LOGIC;
    signal OBRAM_4_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OBRAM_5_ce0 : STD_LOGIC;
    signal OBRAM_5_we0 : STD_LOGIC;
    signal OBRAM_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OBRAM_5_ce1 : STD_LOGIC;
    signal OBRAM_5_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_idle : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_ready : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_idle : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_ready : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_idle : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_ready : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0 : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce : STD_LOGIC;
    signal grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm_state3 : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_77_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_77_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_77_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_77_ce : STD_LOGIC;
    signal grp_fu_81_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_81_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_81_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_81_ce : STD_LOGIC;
    signal grp_fu_85_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_85_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_85_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_85_ce : STD_LOGIC;
    signal grp_fu_89_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_89_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_89_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_89_ce : STD_LOGIC;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lenet5_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        IBRAM_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        IBRAM_ce0 : OUT STD_LOGIC;
        IBRAM_we0 : OUT STD_LOGIC;
        IBRAM_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_layer_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        input_layer_ce0 : OUT STD_LOGIC;
        input_layer_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lenet5_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        IBRAM_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        IBRAM_ce0 : OUT STD_LOGIC;
        IBRAM_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_ce0 : OUT STD_LOGIC;
        OBRAM_we0 : OUT STD_LOGIC;
        OBRAM_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_ce1 : OUT STD_LOGIC;
        OBRAM_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_1_ce0 : OUT STD_LOGIC;
        OBRAM_1_we0 : OUT STD_LOGIC;
        OBRAM_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_1_ce1 : OUT STD_LOGIC;
        OBRAM_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_2_ce0 : OUT STD_LOGIC;
        OBRAM_2_we0 : OUT STD_LOGIC;
        OBRAM_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_2_ce1 : OUT STD_LOGIC;
        OBRAM_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_3_ce0 : OUT STD_LOGIC;
        OBRAM_3_we0 : OUT STD_LOGIC;
        OBRAM_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_3_ce1 : OUT STD_LOGIC;
        OBRAM_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_4_ce0 : OUT STD_LOGIC;
        OBRAM_4_we0 : OUT STD_LOGIC;
        OBRAM_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_4_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_4_ce1 : OUT STD_LOGIC;
        OBRAM_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_5_ce0 : OUT STD_LOGIC;
        OBRAM_5_we0 : OUT STD_LOGIC;
        OBRAM_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_5_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_5_ce1 : OUT STD_LOGIC;
        OBRAM_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_77_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_ce : OUT STD_LOGIC;
        grp_fu_81_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_81_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_81_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_81_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_81_p_ce : OUT STD_LOGIC;
        grp_fu_85_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_85_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_85_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_85_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_85_p_ce : OUT STD_LOGIC;
        grp_fu_89_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_89_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_89_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_89_p_ce : OUT STD_LOGIC );
    end component;


    component lenet5_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        OBRAM_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_ce0 : OUT STD_LOGIC;
        OBRAM_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_1_ce0 : OUT STD_LOGIC;
        OBRAM_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_2_ce0 : OUT STD_LOGIC;
        OBRAM_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_3_ce0 : OUT STD_LOGIC;
        OBRAM_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_4_ce0 : OUT STD_LOGIC;
        OBRAM_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OBRAM_5_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OBRAM_5_ce0 : OUT STD_LOGIC;
        OBRAM_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_77_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_ce : OUT STD_LOGIC;
        grp_fu_81_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_81_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_81_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_81_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_81_p_ce : OUT STD_LOGIC;
        grp_fu_85_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_85_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_85_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_85_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_85_p_ce : OUT STD_LOGIC;
        grp_fu_89_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_89_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_89_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_89_p_ce : OUT STD_LOGIC );
    end component;


    component lenet5_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lenet5_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lenet5_CONVOLUTION_LAYER_1_IBRAM_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    IBRAM_U : component lenet5_CONVOLUTION_LAYER_1_IBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => IBRAM_address0,
        ce0 => IBRAM_ce0,
        we0 => IBRAM_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_d0,
        q0 => IBRAM_q0);

    OBRAM_U : component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OBRAM_address0,
        ce0 => OBRAM_ce0,
        we0 => OBRAM_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_d0,
        q0 => OBRAM_q0,
        address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address1,
        ce1 => OBRAM_ce1,
        q1 => OBRAM_q1);

    OBRAM_1_U : component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OBRAM_1_address0,
        ce0 => OBRAM_1_ce0,
        we0 => OBRAM_1_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_d0,
        q0 => OBRAM_1_q0,
        address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address1,
        ce1 => OBRAM_1_ce1,
        q1 => OBRAM_1_q1);

    OBRAM_2_U : component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OBRAM_2_address0,
        ce0 => OBRAM_2_ce0,
        we0 => OBRAM_2_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_d0,
        q0 => OBRAM_2_q0,
        address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address1,
        ce1 => OBRAM_2_ce1,
        q1 => OBRAM_2_q1);

    OBRAM_3_U : component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OBRAM_3_address0,
        ce0 => OBRAM_3_ce0,
        we0 => OBRAM_3_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_d0,
        q0 => OBRAM_3_q0,
        address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address1,
        ce1 => OBRAM_3_ce1,
        q1 => OBRAM_3_q1);

    OBRAM_4_U : component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OBRAM_4_address0,
        ce0 => OBRAM_4_ce0,
        we0 => OBRAM_4_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_d0,
        q0 => OBRAM_4_q0,
        address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address1,
        ce1 => OBRAM_4_ce1,
        q1 => OBRAM_4_q1);

    OBRAM_5_U : component lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 784,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OBRAM_5_address0,
        ce0 => OBRAM_5_ce0,
        we0 => OBRAM_5_we0,
        d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_d0,
        q0 => OBRAM_5_q0,
        address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address1,
        ce1 => OBRAM_5_ce1,
        q1 => OBRAM_5_q1);

    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48 : component lenet5_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start,
        ap_done => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done,
        ap_idle => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_idle,
        ap_ready => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_ready,
        IBRAM_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0,
        IBRAM_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0,
        IBRAM_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0,
        IBRAM_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_d0,
        input_layer_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_address0,
        input_layer_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_ce0,
        input_layer_q0 => input_layer_q0);

    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56 : component lenet5_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start,
        ap_done => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done,
        ap_idle => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_idle,
        ap_ready => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_ready,
        IBRAM_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0,
        IBRAM_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0,
        IBRAM_q0 => IBRAM_q0,
        OBRAM_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0,
        OBRAM_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0,
        OBRAM_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0,
        OBRAM_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_d0,
        OBRAM_address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address1,
        OBRAM_ce1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1,
        OBRAM_q1 => OBRAM_q1,
        OBRAM_1_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0,
        OBRAM_1_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0,
        OBRAM_1_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0,
        OBRAM_1_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_d0,
        OBRAM_1_address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address1,
        OBRAM_1_ce1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1,
        OBRAM_1_q1 => OBRAM_1_q1,
        OBRAM_2_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0,
        OBRAM_2_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0,
        OBRAM_2_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0,
        OBRAM_2_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_d0,
        OBRAM_2_address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address1,
        OBRAM_2_ce1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1,
        OBRAM_2_q1 => OBRAM_2_q1,
        OBRAM_3_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0,
        OBRAM_3_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0,
        OBRAM_3_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0,
        OBRAM_3_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_d0,
        OBRAM_3_address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address1,
        OBRAM_3_ce1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1,
        OBRAM_3_q1 => OBRAM_3_q1,
        OBRAM_4_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0,
        OBRAM_4_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0,
        OBRAM_4_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0,
        OBRAM_4_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_d0,
        OBRAM_4_address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address1,
        OBRAM_4_ce1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1,
        OBRAM_4_q1 => OBRAM_4_q1,
        OBRAM_5_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0,
        OBRAM_5_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0,
        OBRAM_5_we0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0,
        OBRAM_5_d0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_d0,
        OBRAM_5_address1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address1,
        OBRAM_5_ce1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1,
        OBRAM_5_q1 => OBRAM_5_q1,
        grp_fu_77_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0,
        grp_fu_77_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1,
        grp_fu_77_p_opcode => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_opcode,
        grp_fu_77_p_dout0 => grp_fu_77_p2,
        grp_fu_77_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce,
        grp_fu_81_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0,
        grp_fu_81_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1,
        grp_fu_81_p_opcode => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_opcode,
        grp_fu_81_p_dout0 => grp_fu_81_p2,
        grp_fu_81_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce,
        grp_fu_85_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0,
        grp_fu_85_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1,
        grp_fu_85_p_opcode => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_opcode,
        grp_fu_85_p_dout0 => grp_fu_85_p2,
        grp_fu_85_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce,
        grp_fu_89_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0,
        grp_fu_89_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1,
        grp_fu_89_p_dout0 => grp_fu_89_p2,
        grp_fu_89_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce);

    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67 : component lenet5_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start,
        ap_done => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done,
        ap_idle => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_idle,
        ap_ready => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_ready,
        OBRAM_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0,
        OBRAM_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0,
        OBRAM_q0 => OBRAM_q0,
        OBRAM_1_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0,
        OBRAM_1_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0,
        OBRAM_1_q0 => OBRAM_1_q0,
        OBRAM_2_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0,
        OBRAM_2_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0,
        OBRAM_2_q0 => OBRAM_2_q0,
        OBRAM_3_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0,
        OBRAM_3_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0,
        OBRAM_3_q0 => OBRAM_3_q0,
        OBRAM_4_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0,
        OBRAM_4_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0,
        OBRAM_4_q0 => OBRAM_4_q0,
        OBRAM_5_address0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0,
        OBRAM_5_ce0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0,
        OBRAM_5_q0 => OBRAM_5_q0,
        grp_fu_77_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0,
        grp_fu_77_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1,
        grp_fu_77_p_opcode => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_opcode,
        grp_fu_77_p_dout0 => grp_fu_77_p2,
        grp_fu_77_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce,
        grp_fu_81_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0,
        grp_fu_81_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1,
        grp_fu_81_p_opcode => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_opcode,
        grp_fu_81_p_dout0 => grp_fu_81_p2,
        grp_fu_81_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce,
        grp_fu_85_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0,
        grp_fu_85_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1,
        grp_fu_85_p_opcode => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_opcode,
        grp_fu_85_p_dout0 => grp_fu_85_p2,
        grp_fu_85_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce,
        grp_fu_89_p_din0 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0,
        grp_fu_89_p_din1 => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1,
        grp_fu_89_p_dout0 => grp_fu_89_p2,
        grp_fu_89_p_ce => grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce);

    fadd_32ns_32ns_32_4_full_dsp_1_U48 : component lenet5_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_77_p0,
        din1 => grp_fu_77_p1,
        ce => grp_fu_77_ce,
        dout => grp_fu_77_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U49 : component lenet5_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_81_p0,
        din1 => grp_fu_81_p1,
        ce => grp_fu_81_ce,
        dout => grp_fu_81_p2);

    fadd_32ns_32ns_32_4_full_dsp_1_U50 : component lenet5_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_85_p0,
        din1 => grp_fu_85_p1,
        ce => grp_fu_85_ce,
        dout => grp_fu_85_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U51 : component lenet5_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_89_p0,
        din1 => grp_fu_89_p1,
        ce => grp_fu_89_ce,
        dout => grp_fu_89_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state3) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_ready = ap_const_logic_1)) then 
                    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done, grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    IBRAM_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0, grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            IBRAM_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            IBRAM_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0;
        else 
            IBRAM_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    IBRAM_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            IBRAM_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            IBRAM_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0;
        else 
            IBRAM_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    IBRAM_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            IBRAM_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0;
        else 
            IBRAM_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_1_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_1_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_1_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0;
        else 
            OBRAM_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OBRAM_1_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_1_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_1_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0;
        else 
            OBRAM_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_1_ce1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_1_ce1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1;
        else 
            OBRAM_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_1_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_1_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0;
        else 
            OBRAM_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_2_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_2_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_2_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0;
        else 
            OBRAM_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OBRAM_2_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_2_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_2_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0;
        else 
            OBRAM_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_2_ce1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_2_ce1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1;
        else 
            OBRAM_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_2_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_2_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0;
        else 
            OBRAM_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_3_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_3_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_3_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0;
        else 
            OBRAM_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OBRAM_3_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_3_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_3_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0;
        else 
            OBRAM_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_3_ce1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_3_ce1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1;
        else 
            OBRAM_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_3_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_3_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0;
        else 
            OBRAM_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_4_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_4_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_4_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0;
        else 
            OBRAM_4_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OBRAM_4_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_4_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_4_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0;
        else 
            OBRAM_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_4_ce1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_4_ce1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1;
        else 
            OBRAM_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_4_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_4_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0;
        else 
            OBRAM_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_5_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_5_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_5_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0;
        else 
            OBRAM_5_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OBRAM_5_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_5_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_5_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0;
        else 
            OBRAM_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_5_ce1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_5_ce1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1;
        else 
            OBRAM_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_5_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_5_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0;
        else 
            OBRAM_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_address0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0;
        else 
            OBRAM_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OBRAM_ce0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OBRAM_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0;
        else 
            OBRAM_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_ce1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_ce1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1;
        else 
            OBRAM_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OBRAM_we0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OBRAM_we0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0;
        else 
            OBRAM_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_NS_fsm_state3 <= ap_NS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done)
    begin
        if ((grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done)
    begin
        if ((grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done)
    begin
        if ((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done, ap_CS_fsm_state6)
    begin
        if ((((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg;
    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg;
    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start <= grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg;

    grp_fu_77_ce_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_77_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_77_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce;
        else 
            grp_fu_77_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_77_p0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_77_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_77_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0;
        else 
            grp_fu_77_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_77_p1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_77_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_77_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1;
        else 
            grp_fu_77_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_81_ce_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_81_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_81_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce;
        else 
            grp_fu_81_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_81_p0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_81_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_81_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0;
        else 
            grp_fu_81_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_81_p1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_81_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_81_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1;
        else 
            grp_fu_81_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_85_ce_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_85_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_85_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce;
        else 
            grp_fu_85_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_85_p0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_85_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_85_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0;
        else 
            grp_fu_85_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_85_p1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_85_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_85_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1;
        else 
            grp_fu_85_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_89_ce_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_89_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_89_ce <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce;
        else 
            grp_fu_89_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_89_p0_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_89_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_89_p0 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0;
        else 
            grp_fu_89_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_89_p1_assign_proc : process(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1, grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_89_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_fu_89_p1 <= grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1;
        else 
            grp_fu_89_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    input_layer_address0 <= grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_address0;
    input_layer_ce0 <= grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_ce0;
end behav;
