// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lenet5_lenet5,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.057000,HLS_SYN_LAT=25381,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=5491,HLS_SYN_LUT=5421,HLS_VERSION=2024_2}" *)

module lenet5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_layer_address0,
        input_layer_ce0,
        input_layer_q0,
        output_r
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_layer_address0;
output   input_layer_ce0;
input  [31:0] input_layer_q0;
input  [31:0] output_r;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_CONVOLUTION_LAYER_1_fu_24_ap_start;
wire    grp_CONVOLUTION_LAYER_1_fu_24_ap_done;
wire    grp_CONVOLUTION_LAYER_1_fu_24_ap_idle;
wire    grp_CONVOLUTION_LAYER_1_fu_24_ap_ready;
wire   [9:0] grp_CONVOLUTION_LAYER_1_fu_24_input_layer_address0;
wire    grp_CONVOLUTION_LAYER_1_fu_24_input_layer_ce0;
reg    grp_CONVOLUTION_LAYER_1_fu_24_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_CONVOLUTION_LAYER_1_fu_24_ap_start_reg = 1'b0;
end

lenet5_CONVOLUTION_LAYER_1 grp_CONVOLUTION_LAYER_1_fu_24(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_CONVOLUTION_LAYER_1_fu_24_ap_start),
    .ap_done(grp_CONVOLUTION_LAYER_1_fu_24_ap_done),
    .ap_idle(grp_CONVOLUTION_LAYER_1_fu_24_ap_idle),
    .ap_ready(grp_CONVOLUTION_LAYER_1_fu_24_ap_ready),
    .input_layer_address0(grp_CONVOLUTION_LAYER_1_fu_24_input_layer_address0),
    .input_layer_ce0(grp_CONVOLUTION_LAYER_1_fu_24_input_layer_ce0),
    .input_layer_q0(input_layer_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_CONVOLUTION_LAYER_1_fu_24_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_CONVOLUTION_LAYER_1_fu_24_ap_start_reg <= 1'b1;
        end else if ((grp_CONVOLUTION_LAYER_1_fu_24_ap_ready == 1'b1)) begin
            grp_CONVOLUTION_LAYER_1_fu_24_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_CONVOLUTION_LAYER_1_fu_24_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_CONVOLUTION_LAYER_1_fu_24_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_CONVOLUTION_LAYER_1_fu_24_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_CONVOLUTION_LAYER_1_fu_24_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_CONVOLUTION_LAYER_1_fu_24_ap_start = grp_CONVOLUTION_LAYER_1_fu_24_ap_start_reg;

assign input_layer_address0 = grp_CONVOLUTION_LAYER_1_fu_24_input_layer_address0;

assign input_layer_ce0 = grp_CONVOLUTION_LAYER_1_fu_24_input_layer_ce0;

endmodule //lenet5
