// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lenet5_CONVOLUTION_LAYER_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_layer_address0,
        input_layer_ce0,
        input_layer_q0
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_layer_address0;
output   input_layer_ce0;
input  [31:0] input_layer_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] IBRAM_address0;
reg    IBRAM_ce0;
reg    IBRAM_we0;
wire   [31:0] IBRAM_q0;
reg   [9:0] OBRAM_address0;
reg    OBRAM_ce0;
reg    OBRAM_we0;
wire   [31:0] OBRAM_q0;
reg    OBRAM_ce1;
wire   [31:0] OBRAM_q1;
reg   [9:0] OBRAM_1_address0;
reg    OBRAM_1_ce0;
reg    OBRAM_1_we0;
wire   [31:0] OBRAM_1_q0;
reg    OBRAM_1_ce1;
wire   [31:0] OBRAM_1_q1;
reg   [9:0] OBRAM_2_address0;
reg    OBRAM_2_ce0;
reg    OBRAM_2_we0;
wire   [31:0] OBRAM_2_q0;
reg    OBRAM_2_ce1;
wire   [31:0] OBRAM_2_q1;
reg   [9:0] OBRAM_3_address0;
reg    OBRAM_3_ce0;
reg    OBRAM_3_we0;
wire   [31:0] OBRAM_3_q0;
reg    OBRAM_3_ce1;
wire   [31:0] OBRAM_3_q1;
reg   [9:0] OBRAM_4_address0;
reg    OBRAM_4_ce0;
reg    OBRAM_4_we0;
wire   [31:0] OBRAM_4_q0;
reg    OBRAM_4_ce1;
wire   [31:0] OBRAM_4_q1;
reg   [9:0] OBRAM_5_address0;
reg    OBRAM_5_ce0;
reg    OBRAM_5_we0;
wire   [31:0] OBRAM_5_q0;
reg    OBRAM_5_ce1;
wire   [31:0] OBRAM_5_q1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_idle;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_ready;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_idle;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_ready;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_d0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1;
wire   [1:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_opcode;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1;
wire   [1:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_opcode;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1;
wire   [1:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_opcode;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_idle;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_ready;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0;
wire   [9:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1;
wire   [1:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_opcode;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1;
wire   [1:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_opcode;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1;
wire   [1:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_opcode;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0;
wire   [31:0] grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1;
wire    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce;
reg    grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg;
reg   [5:0] ap_NS_fsm;
wire    ap_NS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_77_p2;
reg   [31:0] grp_fu_77_p0;
reg   [31:0] grp_fu_77_p1;
reg    grp_fu_77_ce;
wire   [31:0] grp_fu_81_p2;
reg   [31:0] grp_fu_81_p0;
reg   [31:0] grp_fu_81_p1;
reg    grp_fu_81_ce;
wire   [31:0] grp_fu_85_p2;
reg   [31:0] grp_fu_85_p0;
reg   [31:0] grp_fu_85_p1;
reg    grp_fu_85_ce;
wire   [31:0] grp_fu_89_p2;
reg   [31:0] grp_fu_89_p0;
reg   [31:0] grp_fu_89_p1;
reg    grp_fu_89_ce;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_CS_fsm_state3;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg = 1'b0;
#0 grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg = 1'b0;
#0 grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg = 1'b0;
end

lenet5_CONVOLUTION_LAYER_1_IBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
IBRAM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(IBRAM_address0),
    .ce0(IBRAM_ce0),
    .we0(IBRAM_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_d0),
    .q0(IBRAM_q0)
);

lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
OBRAM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OBRAM_address0),
    .ce0(OBRAM_ce0),
    .we0(OBRAM_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_d0),
    .q0(OBRAM_q0),
    .address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address1),
    .ce1(OBRAM_ce1),
    .q1(OBRAM_q1)
);

lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
OBRAM_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OBRAM_1_address0),
    .ce0(OBRAM_1_ce0),
    .we0(OBRAM_1_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_d0),
    .q0(OBRAM_1_q0),
    .address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address1),
    .ce1(OBRAM_1_ce1),
    .q1(OBRAM_1_q1)
);

lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
OBRAM_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OBRAM_2_address0),
    .ce0(OBRAM_2_ce0),
    .we0(OBRAM_2_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_d0),
    .q0(OBRAM_2_q0),
    .address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address1),
    .ce1(OBRAM_2_ce1),
    .q1(OBRAM_2_q1)
);

lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
OBRAM_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OBRAM_3_address0),
    .ce0(OBRAM_3_ce0),
    .we0(OBRAM_3_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_d0),
    .q0(OBRAM_3_q0),
    .address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address1),
    .ce1(OBRAM_3_ce1),
    .q1(OBRAM_3_q1)
);

lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
OBRAM_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OBRAM_4_address0),
    .ce0(OBRAM_4_ce0),
    .we0(OBRAM_4_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_d0),
    .q0(OBRAM_4_q0),
    .address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address1),
    .ce1(OBRAM_4_ce1),
    .q1(OBRAM_4_q1)
);

lenet5_CONVOLUTION_LAYER_1_OBRAM_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
OBRAM_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OBRAM_5_address0),
    .ce0(OBRAM_5_ce0),
    .we0(OBRAM_5_we0),
    .d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_d0),
    .q0(OBRAM_5_q0),
    .address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address1),
    .ce1(OBRAM_5_ce1),
    .q1(OBRAM_5_q1)
);

lenet5_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3 grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start),
    .ap_done(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done),
    .ap_idle(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_idle),
    .ap_ready(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_ready),
    .IBRAM_address0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0),
    .IBRAM_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0),
    .IBRAM_we0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0),
    .IBRAM_d0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_d0),
    .input_layer_address0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_address0),
    .input_layer_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_ce0),
    .input_layer_q0(input_layer_q0)
);

lenet5_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start),
    .ap_done(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done),
    .ap_idle(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_idle),
    .ap_ready(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_ready),
    .IBRAM_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0),
    .IBRAM_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0),
    .IBRAM_q0(IBRAM_q0),
    .OBRAM_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0),
    .OBRAM_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0),
    .OBRAM_we0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0),
    .OBRAM_d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_d0),
    .OBRAM_address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address1),
    .OBRAM_ce1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1),
    .OBRAM_q1(OBRAM_q1),
    .OBRAM_1_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0),
    .OBRAM_1_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0),
    .OBRAM_1_we0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0),
    .OBRAM_1_d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_d0),
    .OBRAM_1_address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address1),
    .OBRAM_1_ce1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1),
    .OBRAM_1_q1(OBRAM_1_q1),
    .OBRAM_2_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0),
    .OBRAM_2_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0),
    .OBRAM_2_we0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0),
    .OBRAM_2_d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_d0),
    .OBRAM_2_address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address1),
    .OBRAM_2_ce1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1),
    .OBRAM_2_q1(OBRAM_2_q1),
    .OBRAM_3_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0),
    .OBRAM_3_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0),
    .OBRAM_3_we0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0),
    .OBRAM_3_d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_d0),
    .OBRAM_3_address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address1),
    .OBRAM_3_ce1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1),
    .OBRAM_3_q1(OBRAM_3_q1),
    .OBRAM_4_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0),
    .OBRAM_4_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0),
    .OBRAM_4_we0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0),
    .OBRAM_4_d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_d0),
    .OBRAM_4_address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address1),
    .OBRAM_4_ce1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1),
    .OBRAM_4_q1(OBRAM_4_q1),
    .OBRAM_5_address0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0),
    .OBRAM_5_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0),
    .OBRAM_5_we0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0),
    .OBRAM_5_d0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_d0),
    .OBRAM_5_address1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address1),
    .OBRAM_5_ce1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1),
    .OBRAM_5_q1(OBRAM_5_q1),
    .grp_fu_77_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0),
    .grp_fu_77_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1),
    .grp_fu_77_p_opcode(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_opcode),
    .grp_fu_77_p_dout0(grp_fu_77_p2),
    .grp_fu_77_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce),
    .grp_fu_81_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0),
    .grp_fu_81_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1),
    .grp_fu_81_p_opcode(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_opcode),
    .grp_fu_81_p_dout0(grp_fu_81_p2),
    .grp_fu_81_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce),
    .grp_fu_85_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0),
    .grp_fu_85_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1),
    .grp_fu_85_p_opcode(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_opcode),
    .grp_fu_85_p_dout0(grp_fu_85_p2),
    .grp_fu_85_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce),
    .grp_fu_89_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0),
    .grp_fu_89_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1),
    .grp_fu_89_p_dout0(grp_fu_89_p2),
    .grp_fu_89_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce)
);

lenet5_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3 grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start),
    .ap_done(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done),
    .ap_idle(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_idle),
    .ap_ready(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_ready),
    .OBRAM_address0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0),
    .OBRAM_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0),
    .OBRAM_q0(OBRAM_q0),
    .OBRAM_1_address0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0),
    .OBRAM_1_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0),
    .OBRAM_1_q0(OBRAM_1_q0),
    .OBRAM_2_address0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0),
    .OBRAM_2_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0),
    .OBRAM_2_q0(OBRAM_2_q0),
    .OBRAM_3_address0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0),
    .OBRAM_3_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0),
    .OBRAM_3_q0(OBRAM_3_q0),
    .OBRAM_4_address0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0),
    .OBRAM_4_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0),
    .OBRAM_4_q0(OBRAM_4_q0),
    .OBRAM_5_address0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0),
    .OBRAM_5_ce0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0),
    .OBRAM_5_q0(OBRAM_5_q0),
    .grp_fu_77_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0),
    .grp_fu_77_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1),
    .grp_fu_77_p_opcode(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_opcode),
    .grp_fu_77_p_dout0(grp_fu_77_p2),
    .grp_fu_77_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce),
    .grp_fu_81_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0),
    .grp_fu_81_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1),
    .grp_fu_81_p_opcode(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_opcode),
    .grp_fu_81_p_dout0(grp_fu_81_p2),
    .grp_fu_81_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce),
    .grp_fu_85_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0),
    .grp_fu_85_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1),
    .grp_fu_85_p_opcode(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_opcode),
    .grp_fu_85_p_dout0(grp_fu_85_p2),
    .grp_fu_85_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce),
    .grp_fu_89_p_din0(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0),
    .grp_fu_89_p_din1(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1),
    .grp_fu_89_p_dout0(grp_fu_89_p2),
    .grp_fu_89_p_ce(grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce)
);

lenet5_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_77_p0),
    .din1(grp_fu_77_p1),
    .ce(grp_fu_77_ce),
    .dout(grp_fu_77_p2)
);

lenet5_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_81_p0),
    .din1(grp_fu_81_p1),
    .ce(grp_fu_81_ce),
    .dout(grp_fu_81_p2)
);

lenet5_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_85_p0),
    .din1(grp_fu_85_p1),
    .ce(grp_fu_85_ce),
    .dout(grp_fu_85_p2)
);

lenet5_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_89_p0),
    .din1(grp_fu_89_p1),
    .ce(grp_fu_89_ce),
    .dout(grp_fu_89_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state3) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_ready == 1'b1)) begin
            grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg <= 1'b1;
        end else if ((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_ready == 1'b1)) begin
            grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_ready == 1'b1)) begin
            grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        IBRAM_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        IBRAM_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_address0;
    end else begin
        IBRAM_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        IBRAM_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_IBRAM_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        IBRAM_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_ce0;
    end else begin
        IBRAM_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        IBRAM_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_IBRAM_we0;
    end else begin
        IBRAM_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_1_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_1_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_address0;
    end else begin
        OBRAM_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_1_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_1_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce0;
    end else begin
        OBRAM_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_1_ce1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_ce1;
    end else begin
        OBRAM_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_1_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_1_we0;
    end else begin
        OBRAM_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_2_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_2_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_address0;
    end else begin
        OBRAM_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_2_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_2_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce0;
    end else begin
        OBRAM_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_2_ce1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_ce1;
    end else begin
        OBRAM_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_2_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_2_we0;
    end else begin
        OBRAM_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_3_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_3_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_address0;
    end else begin
        OBRAM_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_3_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_3_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce0;
    end else begin
        OBRAM_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_3_ce1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_ce1;
    end else begin
        OBRAM_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_3_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_3_we0;
    end else begin
        OBRAM_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_4_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_4_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_address0;
    end else begin
        OBRAM_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_4_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_4_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce0;
    end else begin
        OBRAM_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_4_ce1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_ce1;
    end else begin
        OBRAM_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_4_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_4_we0;
    end else begin
        OBRAM_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_5_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_5_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_address0;
    end else begin
        OBRAM_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_5_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_5_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce0;
    end else begin
        OBRAM_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_5_ce1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_ce1;
    end else begin
        OBRAM_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_5_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_5_we0;
    end else begin
        OBRAM_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_address0;
    end else begin
        OBRAM_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OBRAM_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_OBRAM_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce0;
    end else begin
        OBRAM_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_ce1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_ce1;
    end else begin
        OBRAM_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OBRAM_we0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_OBRAM_we0;
    end else begin
        OBRAM_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_77_ce = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_77_ce = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_ce;
    end else begin
        grp_fu_77_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_77_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_77_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din0;
    end else begin
        grp_fu_77_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_77_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_77_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_77_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_77_p_din1;
    end else begin
        grp_fu_77_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_81_ce = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_81_ce = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_ce;
    end else begin
        grp_fu_81_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_81_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_81_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din0;
    end else begin
        grp_fu_81_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_81_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_81_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_81_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_81_p_din1;
    end else begin
        grp_fu_81_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_85_ce = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_85_ce = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_ce;
    end else begin
        grp_fu_85_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_85_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_85_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din0;
    end else begin
        grp_fu_85_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_85_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_85_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_85_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_85_p_din1;
    end else begin
        grp_fu_85_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_89_ce = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_89_ce = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_ce;
    end else begin
        grp_fu_89_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_89_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_89_p0 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din0;
    end else begin
        grp_fu_89_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_89_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_grp_fu_89_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_89_p1 = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_grp_fu_89_p_din1;
    end else begin
        grp_fu_89_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_NS_fsm_state3 = ap_NS_fsm[32'd2];

assign grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start = grp_CONVOLUTION_LAYER_1_Pipeline_ROW_K_COL_K_ROW_COL_fu_56_ap_start_reg;

assign grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start = grp_CONVOLUTION_LAYER_1_Pipeline_VITIS_LOOP_101_2_VITIS_LOOP_102_3_fu_67_ap_start_reg;

assign grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start = grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_ap_start_reg;

assign input_layer_address0 = grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_address0;

assign input_layer_ce0 = grp_CONVOLUTION_LAYER_1_Pipeline_copy_input_2_copy_input_3_fu_48_input_layer_ce0;

endmodule //lenet5_CONVOLUTION_LAYER_1
